# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき(下で見やすくするライン)
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# かっこ閉じ
[[plugins]]
repo = 'Townk/vim-autoclose'

# syntaxエラー表示
[[plugins]]
repo =  'scrooloose/syntastic'

# 末尾の全角と半角空白があれば赤くハイライト
# :FixWhitespaceで全て削除できる
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# git関連、変更・追加・削除箇所がわかる
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# ctrl+pで曖昧検索ができる, 新たにファイル開ける
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# 検索結果の件数を表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'scrooloose/nerdtree'

# vue.js用
[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'chr4/nginx.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
